# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hamux-torch',
                'doc_host': 'https://bhoov.github.io',
                'git_url': 'https://github.com/bhoov/hamux-torch',
                'lib_path': 'hamux_torch'},
  'syms': {'hamux_torch.core': {'hamux_torch.core.foo': ('core.html#foo', 'hamux_torch/core.py')}}}
